import type { Metadata } from 'next'
import '../public/css/globals.scss'

export const metadata: Metadata = {
  title: 'menyaboo',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
